export const UNWATCHED = "UNWATCHED";
export const WATCHED = "WATCHED";
export const ADD_MOVIE = "ADD_MOVIE";
export const DELETE_MOVIE = "DELETE_MOVIE";
export const FILTER_WATCHED_MOVIES = "FILTER_WATCHED_MOVIES";
export const FILTER_UNWATCHED_MOVIES = "FILTER_UNWATCHED_MOVIES";
